name: apogee_server
description: Apogee Habit Tracker Server API built with Dart Frog
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.2

dependencies:
  dart_frog: 1.2.3
  shelf: ^1.4.1
  shelf_cors_headers: ^0.1.5
  postgres: ^3.0.2
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^2.14.1
  uuid: ^4.5.1
  dotenv: ^4.2.0
  apogee_shared:
    path: ../shared/models

dev_dependencies:
  build_runner: ^2.4.13
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0