name: apogee_shared
description: Shared models and utilities for Apogee client and server
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.2

dependencies:
  json_annotation: ^4.9.0
  equatable: ^2.0.5

dev_dependencies:
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  test: ^1.25.8